### ISSUE TITLE
What to do with the existing 'wallet2' code?

### ISSUE THREAD

**Issue by rbrunner7** [seraphis-migration/wallet3#25]
In issue #23 @DangerousFreedom1984 touched the important point of migrating from the current wallet, implemented primarily as `wallet2.h` plus `wallet2.cpp`, to the new Seraphis plus Jamtis world with added support for that. To quote from his issue:

----------

8\) Although all this work is necessary and has to be done somehow, we did not address the elephant in the room, which is how do we make a (smooth) migration into the jamtis/seraphis wallet? I am still building my understanding of the exact tasks to do but so far I see two possible scenarios.
    I) We refactor everything from wallet2 into wallet3 so when someone opens the wallet, it would be calling only methods from wallet3. 
    II) We make them independently and guide the user to the appropriate one. So we would need to make sure that:
	i) all new wallets and transactions are created in the jsp standards.
	ii) it is not possible to open a new and old wallet at the same time.
	iii) if you have an old wallet, the software would smoothly call the wallet2 functions to handle it.
	iv) if you have an old wallet that owns old inputs, wallet2 has a method to pick old inputs and create an output into the jsp standards.
	v) you can re-use your secret key to open the two different wallets, the old and the new. The wallet file should have a tag saying that it is a jsp wallet.

Personally I believe that scenario II) is much more doable. We would only need one interface that would be common to both wallet2/wallet3 so that if the user wants to load an old wallet, it knows which libraries it should use. More or less like in the figure below. Also we could think about something similar if/when we have wallet4 so the code would be already adapted for that.
![class diagram](https://user-images.githubusercontent.com/98208928/198822299-75a1ad42-ea2e-4d8a-bde4-5c1e28f9cf54.png)

**Comment by rbrunner7** [comment]
@UkoeHB commented on the code side / code aspects of this migration, and that's also the point I want to center this issue on:

----------------

`wallet2` should be 100% deprecated after the transition. The seraphis library has fully functioning legacy balance recovery + the ability to spend legacy enotes. The only thing necessary should be migrating `wallet2` wallet file data to the new format(s) so users don't have to re-scan legacy blocks.

**Comment by rbrunner7** [comment]
@DangerousFreedom1984 's answer to this:

---------------

I don't agree with this take. So if wallet2 is completely deprecated it means that besides the review of the seraphis wallet, we would need to review a complete implementation of wallet2 again? How do you see this happening? My proposal was to go in the direction where we have an interface to deal with old/new wallets differently but smoothly.

**Comment by rbrunner7** [comment]
I am fully on the side of koe here. I have worked with the code of `wallet2` quite extensively for my latest PR, and learned first hand what a mess that code is. I really don't see any other way than throwing it away, and deal with the consequences, whatever they are. If there ever was a chance for a clean break, this is it. We leave behind all that talk about "refactoring wallet2" that lead to exactly nothing during years because nobody had the guts (and maybe the necessary time) for that task.

Yes, it's drastic, yes, there will be considerable more code to review, even more so to say, yes it might make the project longer, but as I said, now or never.

That's a statement about code, what this is issue is meant to be about. Of course the UI / UX side is a quite different story, and a different question, and there we will have to offer a migration path for users that is as smooth as possible.

By the way, readers also may check issue #19 about the "principal wallet migration strategy".

**Comment by UkoeHB** [comment]
Maintaining wallet2 is pointless from a technical point of view.

1. Seraphis needs to support spending legacy and seraphis enotes in the same tx to A) provide a seamless UX to users, B) avoid the 'all users sweep all funds' privacy catastrophe that would occur if you can only spend legacy enotes from wallet2 and only spend seraphis enotes from spwallet. Where is the place of wallet2 in the tx construction workflow of: A) select inputs from your joined set of legacy and seraphis enotes, B) construct tx using combined selection of legacy and seraphis enotes?
2. Since legacy enotes can be spent in seraphis txs, balance recovery for the legacy + seraphis eras must be able to reconcile data recovered. One optimization in the seraphis balance recovery process is the seraphis 'chunk builder' only records key images from seraphis txs that contain view tag matches (chunks are built using the 'find received' key that only does view tag checks). This translates to much less data being transmitted between the chunk-building process and the chunk-processing process (significant for third party scanning, and also substantially reduces allocations in local scanning). Importantly, legacy key images from seraphis txs are only recorded in chunks for seraphis txs with view tag matches. When seraphis chunks are processed, the seraphis chunk processor doesn't know what to do with legacy key images, so it just caches all legacy key images that appear in seraphis txs with self-sends (key images of enotes you own will always be attached to self-sends in seraphis txs). These cached legacy key images then must be reconciled against the legacy enotes you own, which are identified by the legacy balance recovery process (a separate workflow from seraphis balance recovery). In other words, the legacy balance recovery workflow completely ignores seraphis txs, and instead relies on key image reconciliation to learn about legacy key images that appear in those txs. All of this for efficiency :). Note that one big advantage of all that is, once the legacy-seraphis transition is over, users only have to do legacy scanning _once_, and then all balance recovery is completely handled by seraphis scanning (unless a reorg pops you below the seraphis-only transition point, which is extremely unlikely).

**Comment by DangerousFreedom1984** [comment]
1) I agree, it could be dangerous if all users decide to sweep all the funds by creating just one transaction as they could be exposed. I was considering adding more functions to wallet2 to handle the new seraphis txs. To select the inputs and ring members the algorithm would work in the same way, they select between old/new inputs but it would be spending from legacy. If you have an old wallet file, the software would open wallet2+seraphis_functions. If you have a new wallet, it would open wallet3.
2) Okay, I'm convinced that it would be better to implement version1+version2 protocols into seraphis (you already have done a big portion of the legacy recovery) instead of doing the opposite. I was just scared about the amount of work but thinking in the future it would actually be less work if we do it now. What about version1 transactions? Did you write something about it? Iit should be much easier than your CLSAG recovery.
Thanks for the answers.

**Comment by UkoeHB** [comment]
> What about version1 transactions? Did you write something about it? Iit should be much easier than your CLSAG recovery.

There is only one seraphis tx type, and it can spend _all_ legacy enotes. Old pre-ringct legacy enotes are [treated the same way](https://github.com/monero-project/research-lab/issues/59) legacy coinbase enotes are treated right now. You make a trivial commitment to the amount (`1 G + a H`) then use that in the CLSAG commitment to zero.

**Comment by rbrunner7** [comment]
It seems pretty well established consensus now among the members of the working group what has to happen with `wallet2` code after the hardfork to Seraphis and Jamtis: It will not be available anymore, because fully deprecated and superseded.

One deciding factor is certainly the excellent support for scanning of "legacy" enotes in the Seraphis library that was already used successfully by @j-berman in some proof-of-concept code. And in general, one only has to compare `wallet2` with the Seraphis library code to see that they are worlds apart: In a way, the Seraphis library is the refactoring and modularization that `wallet2` never got.

We will have to offer support for "legacy" wallet import, but right now I would predict we won't need full `wallet2` for that, only copies of some definitions and some serialization methods from it.

It's very probably that many stakeholders in the Monero "ecosystem" do not yet follow development here close enough to be aware about this consensus and plan, and I expect some hard discussions about it later, but right now this issue here can be closed.
