### ISSUE TITLE
2 blanks or 4 blanks per level for code indentation?

### ISSUE THREAD

**Issue by rbrunner7** [seraphis-migration/wallet3#36]
It's maybe quite a small issue, but probably still merits some discussion, and if we can standardize on something, that's maybe better than each dev just indenting as they personally like best, at least for code files that they start from scratch themselves:

Do we use 2 blanks or 4 blanks for code indentation?

The existing Monero codebase has both cases. I did not count, but I would guess that the files that merely use 2 blanks per level to indent has a majority right now.

@UkoeHB used 4 blanks in his Seraphis library.

I basically see 3 possible stances for Seraphis wallet code:

1) We use only 2 blanks.
2) We use 4 blanks.
3) Devs can decide themselves, at least for files that they start themselves.

Maybe some people see things so relaxed that for them a stance 4) Allow mixing even within the same file would be acceptable. Note however that this would go against a rule stated in Monero's "Contributing" file that asks to respect the formatting of the surrounding code if you do changes.

Opinions?

**Comment by rbrunner7** [comment]
Personally, I am a "2 blanks" type, and for the code we produce at the company where I work, we use that exclusively, and for many years already.

However I admit that 4 blanks per level has one big advantage: You see faster when your code gets too complicated for its own good because your lines start further and further to the right, and you seriously should start to look for ways to slice the big and complicated method that causes this into individual and smaller methods.

**Comment by One-horse-wagon** [comment]
Linus Torvalds demands all linux code be written with 8 blanks per level and a maximum of 3 levels.  His point is if you are looking at code for 20 hours straight, you can still look at it effectively even  after that time.  And, if you need more than 3 levels, your coding is too complicated and needs to be broken down.  Torvalds runs 10,000 developers and a vast code base so his is the voice of experience..

I would suggest setting a minimum of 4 blanks.  If you want to use 6 or 8, feel free because there is not too much difference between 4, 6 and 8.  It all is very easy to read.   And no more than 3 levels.

**Comment by UkoeHB** [comment]
Well obviously I vote for 4 spaces. The most important thing is NO indentation for namespaces. That is one of my pet peeves.

**Comment by rbrunner7** [comment]
Discussed and decided in the second meeting. We go with 4 blanks.
